---

- hosts: "{{ hosts }}"
  become: yes
  gather_facts: no

  vars_files:
    - "vars/services.yml"
#    - "/vars/secrets.yml"

  roles: 
    - { role: db/install_mysql, mysql_version: "{{ mysql_version }}" }
 
        

  
