---

nginx:
  gzip: "on"
  gzip_comp_level: 4
  gzip_min_length: 1024
  gzip_static: "on"
  gzip_types: text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript
  gzip_vary: "on"
  ssl_certificates: selfsigned
  worker_connections: 768
  worker_processes: 4
